spring:
# Dubbo 服务提供者配置
  dubbo:
      application:
        name: shout-gateway-base
      registry:
        address: zookeeper://127.0.0.1:2181
      scan: com.allen.shout.gateway.base.service
# 内置web服务器配置
server:
  port: 8022
