spring:
  datasource:
    dbType: mysql
    url: jdbc:mysql://120.77.203.140:3306/shout_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 5
    maxWait: 60000
    removeAbandoned: true
    removeAbandonedTimeout: 120000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
